services:
  server:
    hostname: matcha-flavoured
    image: itzg/minecraft-server:java25-alpine
    container_name: matcha-flavoured

    network_mode: host
    # ports:
    # - '25565:25565'
    
    environment:
      ONLINE_MODE: false
      MODRINTH_MODPACK: /data/modpack.mrpack
      FABRIC_VERSION: '0.19.5'
      ALLOW_FLIGHT: true
      RCON_CMDS_FIRST_CONNECT: |
        /whitelist off
        /op mxxntype
      MEMORY: '8G'
      ENABLE_AUTOPAUSE: false
      TYPE: MODRINTH
      MOTD: invar-server/0.7.0 | matcha-flavoured | 26.2
      EULA: 'TRUE'
      VERSION: '26.2'
      USE_AIKAR_FLAGS: true
      DIFFICULTY: normal
      VIEW_DISTANCE: 12
      MAX_PLAYERS: 8
      MODE: survival
      # SEED: 0
      # SEED: 7                    # (lithosphere+clifftree) large landmass @ spawn, most explored
      # SEED: -3144770686440785689 # (lithosphere+clifftree) ~2k block wide island @ spawn, large ocean
      # SEED: 8582461431460267422  # (lithosphere+clifftree) lots of islands too choose from

      RCON_CMDS_STARTUP:  |-
        cs center 0 0
        cs shape circle
        cs radius 512
        cs start minecraft:overworld
        cs confirm
    restart: no
    volumes:
    - source: server
      target: /data
      type: bind
    - source: export/matcha-flavoured-latest.mrpack
      target: /data/modpack.mrpack
      type: bind
      read_only: true
    - source: assets/pack.png
      target: /pack.png
      type: bind
      read_only: true
