services:
  server:
    hostname: matcha-flavoured
    image: itzg/minecraft-server:java25-alpine
    container_name: matcha-flavoured

    network_mode: host
    # ports:
    # - '25565:25565'
    
    environment:
      ONLINE_MODE: false
      MODRINTH_MODPACK: /data/modpack.mrpack
      FABRIC_VERSION: '0.19.5'
      ALLOW_FLIGHT: true
      RCON_CMDS_FIRST_CONNECT: |
        op mxxntype
      MEMORY: '8G'
      ENABLE_AUTOPAUSE: false
      TYPE: MODRINTH
      MOTD: invar-server/0.7.0 | matcha-flavoured | 26.2
      EULA: 'TRUE'
      VERSION: '26.2'
      USE_AIKAR_FLAGS: true
      DIFFICULTY: normal
      VIEW_DISTANCE: 12
      MAX_PLAYERS: 8
      MODE: survival
      SEED: 2551431648728912635

      RCON_CMDS_STARTUP:  |-
        simplewhitelist on
        simplewhitelist add mxxntype
        simplewhitelist add exoudueux

        cs center 0 0
        cs shape circle
        cs radius 512
        cs start minecraft:overworld
        cs confirm
    restart: no
    volumes:
    - source: server
      target: /data
      type: bind
    - source: export/matcha-flavoured-latest.mrpack
      target: /data/modpack.mrpack
      type: bind
      read_only: true
