! Mainland biomes.
minecraft:dark_forest             > minecraft:taiga
minecraft:pale_garden             > minecraft:taiga
minecraft:old_growth_pine_taiga   > minecraft:taiga
minecraft:old_growth_spruce_taiga > minecraft:taiga
minecraft:old_growth_birch_forest > minecraft:birch_forest
